
export const AllRoutes = {
    // pages
    List: { path: "/dev/list" },
    ListItem: { path: "/dev/list/:id" },
    Users: { path: "/dev/users" },
    DashboardOverview: { path: "/dev/dashboard/overview" },
    Transactions: { path: "/dev/transactions" },
    Settings: { path: "/dev/settings" },
    Upgrade: { path: "/dev/upgrade" },
    BootstrapTables: { path: "/dev/tables/bootstrap-tables" },
    Billing: { path: "/dev/examples/billing" },
    Invoice: { path: "/dev/examples/invoice" },
    Signin: { path: "/dev/examples/sign-in" },
    Signup: { path: "/dev/examples/sign-up" },
    ForgotPassword: { path: "/dev/examples/forgot-password" },
    ResetPassword: { path: "/dev/examples/reset-password" },
    Lock: { path: "/dev/examples/lock" },
    NotFound: { path: "/dev/examples/404" },
    ServerError: { path: "/dev/examples/500" },

    // docs
    DocsOverview: { path: "/dev/documentation/overview" },
    DocsDownload: { path: "/dev/documentation/download" },
    DocsQuickStart: { path: "/dev/documentation/quick-start" },
    DocsLicense: { path: "/dev/documentation/license" },
    DocsFolderStructure: { path: "/dev/documentation/folder-structure" },
    DocsBuild: { path: "/dev/documentation/build-tools" },
    DocsChangelog: { path: "/dev/documentation/changelog" },

    // components
    Accordions: { path: "/dev/components/accordions" },
    Alerts: { path: "/dev/components/alerts" },
    Badges: { path: "/dev/components/badges" },
    Widgets: { path: "/dev/widgets" },
    Breadcrumbs: { path: "/dev/components/breadcrumbs" },
    Buttons: { path: "/dev/components/buttons" },
    Forms: { path: "/dev/components/forms" },
    Modals: { path: "/dev/components/modals" },
    Navs: { path: "/dev/components/navs" },
    Navbars: { path: "/dev/components/navbars" },
    Pagination: { path: "/dev/components/pagination" },
    Popovers: { path: "/dev/components/popovers" },
    Progress: { path: "/dev/components/progress" },
    Tables: { path: "/dev/components/tables" },
    Tabs: { path: "/dev/components/tabs" },
    Tooltips: { path: "/dev/components/tooltips" },
    Toasts: { path: "/dev/components/toasts" },
    WidgetsComponent: { path: "/dev/components/widgets" }
};